MODELO_CATAFACIL = "CATAFACIL"
MODELO_ANTIGO = "ANTIGO"
MODELO_CONSOLIDADO = "CONSOLIDADO"
MODELO_DESCONHECIDO = "DESCONHECIDO"

MODELOS_VALIDOS = {
    MODELO_CATAFACIL,
    MODELO_ANTIGO,
    MODELO_CONSOLIDADO,
    MODELO_DESCONHECIDO,
}
